name: Publish Nuget

env:
  dotnet_version: 8.x
  nuget_format: snupkg

on:
  workflow_dispatch:

  push:
    tags:
      - '*'
      
jobs:
  build:
    if: ${{ vars.IS_DOT_NET_REPO == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ github.sha }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnet_version }}

      - name: Set Version
        run: echo "Version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Add Github nuget repo
        run: dotnet nuget add source https://nuget.pkg.github.com/TostOrg/index.json --username ${{ secrets.NUGET_GITHUB_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github

      - name: Restore dependencies
        run: dotnet restore "**/*.sln" --no-cache

      - name: Build
        run: dotnet build "**/*.sln" --no-restore --configuration Release -p:Version=${{ env.Version }}

      - name: Test
        run: dotnet test "**/*.sln" --no-build --configuration Release --verbosity normal -p:Version=${{ env.Version }}

      - name: Pack
        run: dotnet pack "**/*.sln" --no-build --configuration Release --include-symbols --include-source -p:SymbolPackageFormat=${{ env.nuget_format }} -p:Version=${{ env.Version }} -o artifacts

      - name: Push
        run: dotnet nuget push "artifacts/*.${{ env.nuget_format }}" --source "github" -k ${{ secrets.GITHUB_TOKEN }} --no-service-endpoint
          
