name: Push closed PR to Main

on:
  workflow_dispatch:

  pull_request:
    types: [ "closed" ]
    branches: [ "main" ]

jobs:
  tag:
    permissions:
      contents: write
    uses: TostOrg/DevOpsTemplates/.github/workflows/git-tag.yml@main
    secrets: 
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      ref: ${{ github.event.pull_request.merge_commit_sha }}

  build:
    needs: tag
    permissions:
      contents: read
    uses: TostOrg/DevOpsTemplates/.github/workflows/dotnet-build.yml@main
    secrets: 
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_GITHUB_USERNAME: ${{ secrets.NUGET_GITHUB_USERNAME }}
    with:
      ref: ${{ github.event.pull_request.merge_commit_sha }}
      version: ${{ needs.tag.outputs.tag }}

  nuget:
    needs: [ "tag", "build" ]
    permissions:
      packages: write
      contents: read
    uses: TostOrg/DevOpsTemplates/.github/workflows/nuget-pack-push.yml@main
    secrets: 
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_GITHUB_USERNAME: ${{ secrets.NUGET_GITHUB_USERNAME }}
    with:
      version: ${{ needs.tag.outputs.tag }}

  delete_prerelease_tags:
    needs: [ "nuget" ]
    permissions:
      contents: write
    uses: TostOrg/DevOpsTemplates/.github/workflows/delete-prerelease-git-tags.yml@main
    with:
      ref: ${{ github.event.pull_request.merge_commit_sha }}
      branch_name: ${{ github.event.pull_request.head.ref }}
    secrets: 
      AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}